<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Linguistics.AssetPipeline</AssemblyName>
    <RootNamespace>Linguistics.AssetPipeline</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Linguistics.Core\Linguistics.Core.csproj" />
  </ItemGroup>
</Project>
